# EXAMPLE secret for local development/testing only.
# DO NOT use these credentials in production. Always create your own.
apiVersion: v1
kind: Secret
metadata:
  name: dolt-credentials
  labels:
    k8s.dolthub.com/watch: ""
stringData:
  admin-user: admin
  admin-password: doltdb123!