include:
  - project: 'REDACTED'
    ref: main
    file: '/docker.yml'
  - project: 'eadp-common/dangerbot'
    ref: main
    file: '/mr-tools.yml'

stages:
  - test

test:
  stage: test
  extends: .dind
  before_script:
    - apk add --no-cache curl bash make git
    - curl -LO https://golang.org/dl/go1.23.linux-amd64.tar.gz
    - tar -C /usr/local -xzf go1.23.linux-amd64.tar.gz
    - export PATH=$PATH:/usr/local/go/bin
    - make kind
    - make tilt
    - make kubectl
    - make cluster
    - make cluster-ctx
  script:
    - tilt ci

