include:
  - project: "REDACTED"
    ref: main
    file: "docker.yml"
  - project: "REDACTED"
    ref: main
    file: "utils.yml"
variables:
  DOLTDB_ENGINE_VERSION: "1.57.2"

# This is a sub-project and will be triggered as a child pipeline from the root .gitlab-ci.yml.
# Variables are declared in the root .gitlab-ci.yml.
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

unit-tests:
  stage: test
  interruptible: true
  image: ${DOCKER_HUB_PROXY}/golang:${GOLANG_VERSION}-alpine
  before_script:
    - !reference [.docker-login, before_script]
    - apk add --no-cache bash make build-base
  script:
    - make test

integration-tests:
  stage: test
  tags:
    - glaas-shared-k8s-dind
  retry: 2 # The DinD runners frequently run into errors.
  timeout: 20m
  image: $DOCKER_PROXY_HOST/docker:27
  services:
    - name: $DOCKER_PROXY_HOST/docker:27-dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://localhost:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  interruptible: true
  before_script:
    - !reference [.docker-login, before_script]
    - apk add --no-cache curl bash make git kubectl build-base
    - make install-go-ci
    - export PATH=${PATH}:/usr/local/go/bin
  script: 
    - echo "Running tests on DoltDB engine version - $DOLTDB_ENGINE_VERSION"
    - make integration-tests-ci

lint:
  stage: test
  image: ${DOCKER_HUB_PROXY}/golangci/golangci-lint:v${GOLANGCI_LINT_VERSION}
  before_script:
    - !reference [.docker-login, before_script]
  script:
    # Generate a code quality report for GitLab to show in MRs.
    - golangci-lint run --issues-exit-code 0 --out-format code-climate > gl-code-quality-report.json
    # Run again (using cached results) to show results in job output.
    - golangci-lint run --color always || { echo 'Linter is configured in .golangci.yaml file.'; false; }
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
    expire_in: 1 month
  allow_failure: true
  interruptible: true
