# GitLab CI yaml reference: https://docs.gitlab.com/ee/ci/yaml/index.html
include:
  - project: "REDACTED"
    ref: main
    file: "/deployment-common.yml"
  - project: "REDACTED"
    ref: main
    file: "utils.yml"

variables:
  # Tooling versions for CI builds.
  # These versions should be driven down through all Makefiles, scripts, and Dockerfiles.
  HELM_VERSION: "3.16.2"
  GOLANG_VERSION: "1.23"
  KUBECTL_VERSION: "1.30.2"
  HELM_DOCS_VERSION: "v1.14.2"
  CONFTEST_VERSION: "0.26.0"
  CHART_TESTING_VERSION: "3.4.0"
  GOLANGCI_LINT_VERSION: "1.60.3"
  # Other variables.
  DOCKER_HUB_PROXY: docker.io
  DOCKER_VERSION: 27
  HELM_PROJECT: "REDACTED"
  PROJECT_NUM: "135"
  HARBOR_REGISTRY: "REDACTED"
  SERVICE_NAME: "dolt-operator"
default:
  tags:
    - glaas-shared-k8s-dind

# Workflow reference: https://docs.gitlab.com/ee/ci/yaml/index.html#workflow
workflow:
  # Rules that determine whether or not a pipeline is created.
  # Rules based on: https://docs.gitlab.com/ee/ci/yaml/index.html#switch-between-branch-pipelines-and-merge-request-pipelines
  rules:
    # Prevent duplicate pipelines if there is an open merge request.
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
      when: never
    # For deploy pipelines, define the release variables.
    - if: $CI_COMMIT_TAG
      variables:
        RELEASE_VERSION: $CI_COMMIT_TAG
    # Match remaining pipeline types.
    - when: always
      variables:
        # The v0.0.0 prefix is to create a valid semver that GitLab Helm registry recognizes.
        RELEASE_VERSION: 0.0.0-${CI_PIPELINE_ID}

.deploy:manual:
  rules:
    - if: $CI_COMMIT_REF_PROTECTED != "true" && ($CI_COMMIT_BRANCH == null || $CI_COMMIT_TAG == null)
      when: manual
  allow_failure: true
  interruptible: true

operator:test:
  trigger:
    include:
      - local: .gitlab-operator-ci.yml
    strategy: depend
  rules:
    # In merge requests pipelines, only trigger the sub-project tests if there are code changes.
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - "api/**/*"
        - "cmd/**/*"
        - "internal/**/*"
        - "pkg/**/*"
        - "hack/**/*"
        - "config/**/*"
        - "Tiltfile"
        - "go.mod"
        - "go.sum"
    # Trigger the tests for all other pipeline types.
    - if: $CI_PIPELINE_SOURCE != "merge_request_event"
# Only run when branch is non-protected and the project is not a fork and only on branches (not merge requests)
image:deploy:manual:
  extends:
    - .image:deploy
    - .deploy:manual

# Only run when branch is non-protected and the project is not a fork and only on branches (not merge requests)
chart:deploy:manual:
  extends:
    - .chart-release
    - .deploy:manual
