include:
  - project: 'REDACTED'
    ref: main
    file: '/docker.yml'
  - project: 'eadp-common/dangerbot'
    ref: main
    file: '/mr-tools.yml'

stages:
  - test

#TODO: Fix CI pipeline
test:
  stage: test
  extends: .dind
  before_script:
    - apk add --no-cache curl bash make git go
    - make kind
    - make tilt
    - make kubectl
    - make cluster
    - make cluster-ctx
  script:
    - tilt ci

