kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "doltdb-operator.fullname" . }}
  labels:
  {{- include "doltdb-operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "doltdb-operator.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "doltdb-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
