# permissions for end users to edit grants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: doltdb-operator
    app.kubernetes.io/managed-by: kustomize
  name: grant-editor-role
rules:
- apiGroups:
  - k8s.dolthub.com
  resources:
  - grants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.dolthub.com
  resources:
  - grants/status
  verbs:
  - get
