# permissions for end users to edit snapshots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dolt-operator
    app.kubernetes.io/managed-by: kustomize
  name: Snapshot-editor-role
rules:
- apiGroups:
  - REDACTED
  resources:
  - snapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - REDACTED
  resources:
  - snapshots/status
  verbs:
  - get
