
include:
  - project: "REDACTED"
    ref: main
    file: "docker.yml"
  - project: "REDACTED"
    ref: main
    file: "utils.yml"

# This is a sub-project and will be triggered as a child pipeline from the root .gitlab-ci.yml.
# Variables are declared in the root .gitlab-ci.yml.
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

.make:
  extends:
    - .dind
  retry: 2 # The DinD runners frequently run into errors.
  before_script:
    - !reference [.docker-login, before_script]
    - apk add --no-cache git bash make

verify-docs:
  extends: .make
  script: cd charts && make verify-docs

lint:
  extends: .make
  script: cd charts && make lint

check-policy:
  extends: .make
  script: cd charts && make check-policy

check-policy-strict:
  extends: .make
  allow_failure: true
  script: cd charts && make check-policy-strict
