apiVersion: k8s.dolthub.com/v1alpha
kind: BackupSchedule
metadata:
  name: backupschedule-sample
  labels:
    app.kubernetes.io/name: doltdb-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  doltDBRef:
    name: doltdb-sample
  schedule: "0 2 * * *"
  storage:
    local:
      path: /var/backups/dolt
