apiVersion: k8s.dolthub.com/v1alpha
kind: Snapshot
metadata:
  labels:
    app.kubernetes.io/name: doltdb-operator
    app.kubernetes.io/managed-by: kustomize
  name: dolt
  namespace: default
spec:
  doltDBRef:
    name: dolt
    namespace: default
  frequencySchedule: "1 * * * *"