apiVersion: k8s.dolthub.com/v1alpha
kind: DoltDB
metadata:
  name: dolt
  namespace: default
spec:
  engineVersion: 1.57.2
  image: "dolthub/dolt"
  replicas: 2
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
  storage:
    size: "10Gi"
    volumeSnapshot: "dolt-sc"
  server:
    behavior:
      autoGCBehavior:
        enabled: true
    cluster:
      remotesAPI:
        port: 50051
    logLevel: "warning"
    listener:
      host: 0.0.0.0
      maxConnections: 2048
      port: 3306
    metrics:
      enabled: true
      labels:
        app: dolt
  globalConfig:
    disableClientUsageMetricsCollection: true
    commitAuthor:
      name: "dolt kubernetes deployment"
      email: "dolt@kubernetes.deployment"
  replication:
    enabled: true
    primary: 
      podIndex: 0
      automaticFailover: true