apiVersion: k8s.dolthub.com/v1alpha
kind: Backup
metadata:
  name: backup-sample
  labels:
    app.kubernetes.io/name: doltdb-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  doltDBRef:
    name: doltdb-sample
  storage:
    local:
      path: /var/backups/dolt
