##@ Development

CLUSTER ?= dolt
KIND_CONFIG ?= hack/manifests/kind/kind.yaml
KIND_CONFIG_CI ?= hack/manifests/kind/kind-ci.yaml

ENV ?= \
	DOLTDB_ENGINE_VERSION=$(DOLTDB_ENGINE_VERSION)

.PHONY: cluster
cluster:
	$(KIND) create cluster --name $(CLUSTER) --config $(KIND_CONFIG)

.PHONY: cluster-ci
cluster-ci:
	if kind get clusters | grep -q "${CLUSTER}"; then \
		echo "Cluster ${CLUSTER} already exists."; \
	else \
		echo "Cluster ${CLUSTER} does not exist. Creating it now..."; \
		$(KIND) create cluster --name $(CLUSTER) --config $(KIND_CONFIG_CI); \
	fi

.PHONY: cluster-delete
cluster-delete:
	$(KIND) delete cluster --name $(CLUSTER)

.PHONY: cluster-ctx
cluster-ctx: ## Sets cluster context.
	$(KUBECTL) config use-context kind-$(CLUSTER)

.PHONY: test-int
test-int: ## Run tests.
	$(ENV) go test ./internal/controller/... -v -ginkgo.v --coverprofile=cover.out --timeout 30m

.PHONY: test
test: ## Run tests.
	CGO_ENABLED=1 go test $$(go list ./...| grep -v /internal/controller) -race -coverprofile cover.out

.PHONY: manifests
manifests: controller-gen ## Generate WebhookConfiguration, ClusterRole and CustomResourceDefinition objects.
	@# Remove all Kustomize config generated by kubebuilder except for the samples.
	! test -d config/samples || cp config/samples/* charts/dolt-operator/samples
	@# Clean the generated directory.
	rm -rf charts/dolt-operator/generated/*

	$(CONTROLLER_GEN) rbac:roleName=manager-role crd webhook paths="./..." \
		output:crd:artifacts:config=config/crd/bases \
		output:rbac:artifacts:config=config/rbac \
		output:webhook:artifacts:config=config/webhook

	$(CONTROLLER_GEN) rbac:roleName=manager-role crd webhook paths="./..." \
		output:crd:artifacts:config=charts/dolt-operator/generated/crd \
		output:rbac:artifacts:config=charts/dolt-operator/generated/rbac \
		output:webhook:artifacts:config=charts/dolt-operator/generated/webhook

.PHONY: generate
generate: controller-gen ## Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.
	$(CONTROLLER_GEN) object:headerFile="hack/boilerplate.go.txt" paths="./..."

.PHONY: fmt
fmt: ## Run go fmt against code.
	go fmt ./...

.PHONY: vet
vet: ## Run go vet against code.
	go vet ./...

.PHONY: lint
lint: golines golangci-lint ## Run golangci-lint linter
	$(GOLINES) --max-len=140 --tab-len=2 --dry-run --chain-split-dots --shorten-comments pkg/ internal/ cmd/ api/
	$(GOLANGCI_LINT) run -v --color always
	

.PHONY: lint-fix
lint-fix: golines golangci-lint ## Run golangci-lint linter and perform fixes
	$(GOLINES) --max-len=140 --tab-len=2 --chain-split-dots --shorten-comments --write-output pkg/ internal/ cmd/ api/
	$(GOLANGCI_LINT) run --fix -v

.PHONY: tiltdev
tiltdev:
	make cluster-ci CLUSTER=doltdev cluster-ctx CLUSTER=doltdev
	tilt up -f Tiltfile.dev

.PHONY: tilttest
tilttest:
	make cluster-ci CLUSTER=dolttest cluster-ctx CLUSTER=dolttest
	tilt up

.PHONY: tiltci
tiltci: cluster-ctx
	tilt ci

.PHONY: integration-tests-ci
integration-tests-ci: kind install-tilt-ci install-kustomize-ci cluster-ci cluster-ctx
	tilt ci	
