##@ Development

CLUSTER ?= dolt
KIND_CONFIG ?= hack/manifests/kind/kind.yaml

.PHONY: cluster
cluster:
	$(KIND) create cluster --name $(CLUSTER) --config $(KIND_CONFIG)

.PHONY: cluster-ci
cluster-ci:
	if kind get clusters | grep -q "${CLUSTER}"; then \
		echo "Cluster ${CLUSTER} already exists."; \
	else \
		echo "Cluster ${CLUSTER} does not exist. Creating it now..."; \
		$(KIND) create cluster --name $(CLUSTER);  \
	fi

.PHONY: cluster-delete
cluster-delete:
	$(KIND) delete cluster --name $(CLUSTER)

.PHONY: cluster-ctx
cluster-ctx: ## Sets cluster context.
	$(KUBECTL) config use-context kind-$(CLUSTER)

.PHONY: test-int
test-int: ## Run tests.
	go test ./internal/controller/... -v -ginkgo.v --coverprofile=cover.out --timeout 10m

.PHONY: test
test: ## Run tests.
	go test $$(go list ./...| grep -v /internal/controller) -race -coverprofile cover.out

.PHONY: manifests
manifests: controller-gen ## Generate WebhookConfiguration, ClusterRole and CustomResourceDefinition objects.
	@# Remove all Kustomize config generated by kubebuilder except for the samples.
	! test -d config/samples || cp config/samples/* charts/dolt-operator/samples
	@# Clean the generated directory.
	rm -rf charts/dolt-operator/generated

	$(CONTROLLER_GEN) rbac:roleName=manager-role crd webhook paths="./..." \
	output:crd:artifacts:config=config/crd/bases \
	output:rbac:artifacts:config=config/rbac \
	output:webhook:artifacts:config=config/webhook

	$(CONTROLLER_GEN) rbac:roleName=manager-role crd webhook paths="./..." 
	output:crd:artifacts:config=charts/dolt-operator/generated/crd \
	output:rbac:artifacts:config=charts/dolt-operator/generated/rbac \
	output:webhook:artifacts:config=charts/dolt-operator/generated/webhook \

.PHONY: generate
generate: controller-gen ## Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.
	$(CONTROLLER_GEN) object:headerFile="hack/boilerplate.go.txt" paths="./..."

.PHONY: fmt
fmt: ## Run go fmt against code.
	go fmt ./...

.PHONY: vet
vet: ## Run go vet against code.
	go vet ./...

.PHONY: lint
lint: golangci-lint ## Run golangci-lint linter
	$(GOLANGCI_LINT) run

.PHONY: lint-fix
lint-fix: golangci-lint ## Run golangci-lint linter and perform fixes
	$(GOLANGCI_LINT) run --fix

tiltdev: cluster-ctx
	tilt up

tiltci: cluster-ctx
	tilt ci
